name: Publish Container Image to GCP Artifact Registry

on:
  push:
    branches:
      - "master"
    tags:
      - "**"

jobs:
  build-push-registry:
    runs-on: ubuntu-latest

    env:
      REGION: europe-west3-docker.pkg.dev
      PROJECT_ID: cluster-340122
      REPOSITORY: container-images

    steps:
      - uses: actions/checkout@v5

      - name: Fetch Repository Name
        id: repo-name
        run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGION }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.REPOSITORY_NAME }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - id: auth
        uses: google-github-actions/auth@v3
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"
      - uses: google-github-actions/setup-gcloud@v3

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker $REGION --quiet

      - name: Build and Push Docker Image to Artifact Registry
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
